name: Documentation
on:
  pull_request:
    paths:
      - '.github/workflows/documentation.yml'
      - 'package.json'
      - 'docs/**'
      - 'lib'
      - 'test'
      - 'website.js'
      - 'CHANGELOG.md'
  push:
    branches:
      - master
    paths:
      - '.github/workflows/documentation.yml'
      - 'package.json'
      - 'docs/**'
      - 'lib'
      - 'test'
      - 'website.js'
      - 'CHANGELOG.md'
permissions:
  contents: read

jobs:
  test-documentation:
    runs-on: ubuntu-20.04
    name: Test Generating Docs
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0

      - name: Setup node
        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # v3.5.1
        with:
          node-version: 16

      - run: npm install
      - run: npm run docs:clean
      - run: npm run docs:generate
